### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by ZadenRB** [guillaumewuip/hubot-wit-helper#1]
When trying to use
`const witHelper = require('hubot-wit-helper');`
It results in a crash saying `require(...)` is not a function. Any fixes for this? I have used npm to install hubot-wit-helper.

**Comment by guillaumewuip** [comment]
Hi @ZadenRB, thanks for your issue. Are you using NodeJS v6 or more ?

**Comment by ZadenRB** [comment]
@guillaumewuip Yes. NodeJS 6.9.1

**Comment by guillaumewuip** [comment]
Ok @ZadenRB , strange. Can you provide the full code you use ?

**Comment by ZadenRB** [comment]
@guillaumewuip 

``` js
'use strict';

const Wit = require('node-wit').Wit;
const witHelper = require('hubot-wit-helper');

const accessToken = 'Not shown for obv reasons';

const firstEntityValue = (entities, entity) => {
  const val = entities && entities[entity] &&
    Array.isArray(entities[entity]) &&
    entities[entity].length > 0 &&
    entities[entity][0].value
  ;
  if (!val) {
    return null;
  }
  return typeof val === 'object' ? val.value : val;
};

const actions = {
  send(request, response) {
    const {sessionId, context, entities} = request;
    const {text, quickreplies} = response;
    return new Promise(function(resolve, reject) {
      console.log(JSON.stringify(response.text));
      return resolve();
    });
  },
  agenda({context, entities}) {
    return new Promise(function(resolve, reject) {
      var date = firstEntityValue(entities, "date");
      return resolve(context);
    });
  },
};

const bot = robot => {

  const witRobot = new witHelper.Robot(accessToken, actions, robot);

  witRobot.respond(/(.*)/gi, (err, context, res) => {

  console.log(`[USER] ${witRobot.getMsg(res)}`);

  if(err) {
    console.error(err);
    return;
  }
});

};

module.exports = bot;
```

It's essentially just the example code.

**Comment by guillaumewuip** [comment]
@ZadenRB This code works well on my computer. It may be a problem with hubot ?
I have just tested it with the last version of Hubot and the docs : https://hubot.github.com/docs/.

**Comment by ZadenRB** [comment]
@guillaumewuip Alright, thanks. I'll look into it

**Comment by ZadenRB** [comment]
@guillaumewuip Any ideas as to what with hubot could be causing this? I haven't been able to find any issues. If it is relevant, I am using the webby flowdock adapter for hubot.

**Comment by ZadenRB** [comment]
Turned out to be an issue with node-wit. Resolved now. Thanks for your help.

**Comment by JigSawFr** [comment]
@ZadenRB Can you explain me what was the problem, i'm actually facing the same problem ❓

**Comment by ZadenRB** [comment]
@JigSawFr The issue was that I had node-wit in external-scripts.json, and was requiring node-wit. Node-wit only needed to be in package.json as a dependency.
